drop user delphix2 cascade;
create user delphix2 identified by delphix2;
drop role delphix_role;
create role delphix_role;
grant create session to delphix_role;
grant select on v_$active_session_history to delphix_role;
grant select on v_$archive_dest_status to delphix_role;
grant select on v_$archived_log to delphix_role;
grant select on v_$backup_datafile to delphix_role;
grant select on v_$backup_piece to delphix_role;
grant select on v_$backup_set to delphix_role;
grant select on v_$controlfile to delphix_role;
grant select on v_$database to delphix_role;
grant select on v_$database_incarnation to delphix_role;
grant select on v_$datafile to delphix_role;
grant select on v_$datafile_header to delphix_role;
grant select on v_$license to delphix_role;
grant select on v_$log to delphix_role;
grant select on v_$logfile to delphix_role;
grant select on v_$parameter to delphix2;
grant select on v_$rman_backup_job_details to delphix_role;
grant select on v_$rman_configuration to delphix_role;
grant select on v_$session to delphix_role;
grant select on v_$sqltext to delphix_role;
grant select on v_$standby_log to delphix_role;
grant select on v_$sysstat to delphix_role;
grant select on v_$tablespace to delphix_role;
grant select on v_$tempfile to delphix_role;
grant select on v_$thread to delphix_role;
grant select on gv_$thread to delphix_role;
grant select on v_$transportable_platform to delphix_role;
grant select on v_$transaction to delphix_role;
grant delphix_role to delphix2;
